### PR TITLE
add  @:transitive for  haxe 4.2

### PR DESCRIPTION
**Pull request by nanjizal**

### CODE REVIEW

**Comment by nanjizal** [comment]
adds @:transitive to allow build on c++.

**Comment by haxiomic** [comment]
Hey sorry I've not reviewed this yet

I'm not too familiar with @:transitive, what does this change enable? Could you give an example with what didn't work before and what works now?

Otherwise the change itself looks fine and happy to merge when I understand better :)

**Comment by nanjizal** [comment]
Haxe changed abstracts late in release of Haxe 4.2.
This change was required after 4.2.0-rc.1+7dc565e63
In the manual it says 
"By design, implicit casts are not transitive"
https://haxe.org/manual/types-abstract-implicit-casts.html
but it was not strictly true, Dimittri Maganov changed abstracts ( for c++ & static targets, no impact on js ).

Transitive
"No runtime implications. You can think of it like @:forward metas - by default an abstract is opaque one, it hides everything about underlying type and to expose parts of it (fields, constructor, variance and so on) you add corresponding meta. Same with @:transitive (it could have been named @:forward.cast or something like this) - you add it to say that when it comes to casts an abstract does not care much and can be removed from the picture." - quote vonagam 

The change means that @:transitive abstracts will disappear totally at runtime, otherwise they will not super inherit forwards and must be partially kept?  I think.  Basically the change is required to maintain support for the code on Haxe > 4.2  for c++ target ( makes no difference to js code ).  It's just down to allowing full inheritance and thus full removal at runtime. The half breaking change to fix code to be compatible with spec, was really annoying as it messed a lot of my abstracts and it was done very close to release to 4.2.

**Comment by nanjizal** [comment]
I made some initial errors with my first commit I was just eager to get it running again, but the current pull should be correct and you will not see difference on js target.

**Comment by haxiomic** [comment]
Thanks you :)

**Pull request merged**
